---
- name: Install docker
  hosts: localhost
  become: yes
  tasks:
    - name: Remove old packege
      apt:
        name: [
        'docker',
        'docker-engine',
        'docker.io',
        'containerd',
        'runc']
        autoremove: yes
        state: absent

    - name: Install package prerequisites
      apt:
        name: [
        'apt-transport-https',
        'ca-certificates',
        'curl',
        'gnupg2',
        'software-properties-common',
        ]
        update_cache: true

    - name: Add key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Check if docker source file exists
      stat:
        path: /etc/apt/sources.list.d/docker.list
      register: docker_source
  

    - name: Add repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian/ {{ ansible_lsb.codename  }} stable
        state: present
        filename: docker
      when: docker_source.stat.exists == false

    - name: Install
      apt:
        name: [
        'docker-ce',
        'docker-ce-cli',
        'containerd.io',
        ]
        update_cache: true

    - name: Add group docker
      group:
        name: docker
        state: present

    - name: Add '{{ ansible_env.LOGNAME  }}' to docker group
      user:
        name: maxi
        groups: docker
        append: yes
